data_path: './dataset_files'
load_col:
    inter: ['user_id', 'item_id', 'rating', 'timestamp']
    item: ["item_id", "title"]
title_col:
    'title'
text_col:
    ['title', 'categories']
MAX_ITEM_LIST_LENGTH: 10